server:
  ssl:
    enabled: false
    key-store: smartlink.p12
    key-store-type: PKCS12
    key-alias: smartlink
    key-password: chinatown
    key-store-password: chinatown
  port: 8080
spring:
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: false
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        jdbc:
          lob:
            non_contextual_creation: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        default-requeue-rejected: false
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: china_town
    driverClassName: org.postgresql.Driver
    h2:
      console:
        enabled: true
